"""Professional PDF invoice builder using fpdf2.

Supports:
- Customizable company info (name, address, phone, email, logo)
- Multi-currency (INR, USD, EUR, GBP, AED, SGD, etc.)
- Configurable tax label (GST, VAT, Sales Tax)
- Custom payment terms and footer
- Locale-aware number formatting
"""
from fpdf import FPDF


# PDF-safe currency symbols (Helvetica-compatible ASCII fallbacks)
PDF_CURRENCY_MAP = {
    "₹": "Rs.",
    "€": "EUR ",
    "£": "GBP ",
    "¥": "JPY ",
}

# Currency locale formatting
LOCALE_FORMATS = {
    "en-IN": {"decimal": ".", "thousands": ",", "date": "%d %b %Y"},
    "en-US": {"decimal": ".", "thousands": ",", "date": "%b %d, %Y"},
    "en-GB": {"decimal": ".", "thousands": ",", "date": "%d %b %Y"},
    "en-EU": {"decimal": ",", "thousands": ".", "date": "%d.%m.%Y"},
    "en-AE": {"decimal": ".", "thousands": ",", "date": "%d %b %Y"},
    "en-SG": {"decimal": ".", "thousands": ",", "date": "%d %b %Y"},
}


def _pdf_safe(text):
    """Replace Unicode characters that Helvetica can't render."""
    for unicode_char, ascii_fallback in PDF_CURRENCY_MAP.items():
        text = text.replace(unicode_char, ascii_fallback)
    return text


def _format_amount(amount, currency_symbol, locale="en-IN"):
    """Format amount with currency symbol and locale-aware separators."""
    fmt = LOCALE_FORMATS.get(locale, LOCALE_FORMATS["en-IN"])
    # Use PDF-safe currency symbol
    safe_symbol = PDF_CURRENCY_MAP.get(currency_symbol, currency_symbol)
    # Format with 2 decimal places
    parts = f"{amount:,.2f}".split(".")
    int_part = parts[0].replace(",", fmt["thousands"])
    dec_part = parts[1]
    return f"{safe_symbol}{int_part}{fmt['decimal']}{dec_part}"


class InvoicePDF(FPDF):
    """Custom PDF class for OmniDesk invoices."""

    def __init__(self, settings):
        super().__init__()
        self.settings = settings
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        pass  # We handle header manually in build()

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        footer_text = _pdf_safe(self.settings.get("invoice_footer", "Thank you for your business"))
        self.cell(0, 5, footer_text, align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, "Generated by OmniDesk", align="C")


def build_invoice_pdf(invoice_data, items, order, settings):
    """Build a professional PDF invoice.

    Args:
        invoice_data: dict with invoice_number, subtotal, tax_rate, tax_amount, total_amount, due_date, created_at
        items: list of dicts with product_name, sku, quantity, unit_price, total_price
        order: dict with order_number, customer_name, customer_email, customer_phone, customer_address
        settings: dict from org_settings (company_name, currency_symbol, tax_label, etc.)

    Returns:
        bytes: PDF file content
    """
    currency = settings.get("currency_symbol", "₹")
    locale = settings.get("locale", "en-IN")
    tax_label = settings.get("tax_label", "GST")

    pdf = InvoicePDF(settings)
    pdf.add_page()

    # ── Company Header ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(37, 99, 235)  # Blue
    company_name = settings.get("company_name", "OmniDesk")
    pdf.cell(100, 10, company_name, new_x="RIGHT")

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 41, 59)  # Dark
    pdf.cell(0, 10, "INVOICE", align="R", new_x="LMARGIN", new_y="NEXT")

    # Company details (below name)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)  # Gray
    company_address = settings.get("company_address", "")
    company_phone = settings.get("company_phone", "")
    company_email = settings.get("company_email", "")
    details_parts = [p for p in [company_address, company_phone, company_email] if p]
    if details_parts:
        pdf.cell(0, 5, " | ".join(details_parts), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # ── Divider ─────────────────────────────────────────────────────
    pdf.set_draw_color(226, 232, 240)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # ── Invoice Meta + Bill To (side by side) ───────────────────────
    y_start = pdf.get_y()

    # Left: Invoice Details
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(60, 5, "INVOICE DETAILS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(60, 6, invoice_data["invoice_number"], new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(60, 5, f"Date: {invoice_data['created_at']}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(60, 5, f"Due: {invoice_data['due_date'] or 'On receipt'}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(60, 5, f"Order: {order['order_number']}", new_x="LMARGIN", new_y="NEXT")

    y_after_left = pdf.get_y()

    # Right: Bill To
    pdf.set_y(y_start)
    pdf.set_x(120)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(70, 5, "BILL TO", new_x="LEFT", new_y="NEXT")
    pdf.set_x(120)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(70, 6, order.get("customer_name", ""), new_x="LEFT", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    if order.get("customer_address"):
        pdf.set_x(120)
        pdf.cell(70, 5, order["customer_address"], new_x="LEFT", new_y="NEXT")
    if order.get("customer_email"):
        pdf.set_x(120)
        pdf.cell(70, 5, order["customer_email"], new_x="LEFT", new_y="NEXT")
    if order.get("customer_phone"):
        pdf.set_x(120)
        pdf.cell(70, 5, order["customer_phone"], new_x="LEFT", new_y="NEXT")

    y_after_right = pdf.get_y()
    pdf.set_y(max(y_after_left, y_after_right) + 8)

    # ── Items Table ─────────────────────────────────────────────────
    # Table header
    pdf.set_fill_color(30, 41, 59)  # Dark header
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)

    col_widths = [12, 78, 25, 35, 40]  # #, Item, Qty, Unit Price, Amount
    headers = ["#", "Item", "Qty", "Unit Price", "Amount"]
    aligns = ["C", "L", "C", "R", "R"]

    for i, (w, h, a) in enumerate(zip(col_widths, headers, aligns)):
        pdf.cell(w, 8, h, align=a, fill=True,
                 new_x="RIGHT" if i < len(headers) - 1 else "LMARGIN",
                 new_y="TOP" if i < len(headers) - 1 else "NEXT")

    # Table rows
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(51, 65, 85)
    fill = False
    for idx, item in enumerate(items, 1):
        if fill:
            pdf.set_fill_color(248, 250, 252)  # Light gray stripe
        else:
            pdf.set_fill_color(255, 255, 255)

        row_data = [
            str(idx),
            f"{item['product_name']} ({item['sku']})",
            str(item["quantity"]),
            _format_amount(item["unit_price"], currency, locale),
            _format_amount(item["total_price"], currency, locale),
        ]
        for i, (w, d, a) in enumerate(zip(col_widths, row_data, aligns)):
            pdf.cell(w, 7, d, align=a, fill=True,
                     new_x="RIGHT" if i < len(row_data) - 1 else "LMARGIN",
                     new_y="TOP" if i < len(row_data) - 1 else "NEXT")
        fill = not fill

    # Bottom border
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # ── Totals ──────────────────────────────────────────────────────
    totals_x = 120
    totals_label_w = 40
    totals_val_w = 40

    # Subtotal
    pdf.set_x(totals_x)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(totals_label_w, 7, "Subtotal", align="R")
    pdf.cell(totals_val_w, 7, _format_amount(invoice_data["subtotal"], currency, locale),
             align="R", new_x="LMARGIN", new_y="NEXT")

    # Tax
    if invoice_data["tax_rate"] > 0:
        pdf.set_x(totals_x)
        pdf.cell(totals_label_w, 7, f"{tax_label} ({invoice_data['tax_rate']}%)", align="R")
        pdf.cell(totals_val_w, 7, _format_amount(invoice_data["tax_amount"], currency, locale),
                 align="R", new_x="LMARGIN", new_y="NEXT")

    # Total line
    pdf.set_draw_color(30, 41, 59)
    pdf.line(totals_x, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_x(totals_x)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(totals_label_w, 9, "TOTAL", align="R")
    pdf.cell(totals_val_w, 9, _format_amount(invoice_data["total_amount"], currency, locale),
             align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)

    # ── Payment Terms & Notes ───────────────────────────────────────
    payment_terms = settings.get("payment_terms", "Net 30")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, "PAYMENT TERMS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(0, 5, payment_terms, new_x="LMARGIN", new_y="NEXT")

    if invoice_data.get("notes"):
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 5, "NOTES", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(0, 5, invoice_data["notes"])

    # Return PDF as bytes
    return pdf.output()
