"""Report builder — generates HTML reports from markdown + Chart.js configs."""
import json
from datetime import datetime


HTML_SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — OmniDesk Report</title>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #f8f9fa; color: #212529; line-height: 1.6;
    max-width: 960px; margin: 0 auto; padding: 20px;
  }}
  .report-header {{
    background: linear-gradient(135deg, #1a73e8, #0d47a1);
    color: white; padding: 30px; border-radius: 12px; margin-bottom: 24px;
  }}
  .report-header h1 {{ font-size: 1.8em; margin-bottom: 4px; }}
  .report-header .meta {{ opacity: 0.85; font-size: 0.9em; }}
  .report-body {{
    background: white; padding: 32px; border-radius: 12px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  }}
  .report-body h1 {{ font-size: 1.6em; color: #1a73e8; margin: 24px 0 12px; border-bottom: 2px solid #e8eaed; padding-bottom: 8px; }}
  .report-body h2 {{ font-size: 1.3em; color: #333; margin: 20px 0 10px; }}
  .report-body h3 {{ font-size: 1.1em; color: #555; margin: 16px 0 8px; }}
  .report-body table {{
    width: 100%; border-collapse: collapse; margin: 16px 0;
    font-size: 0.95em;
  }}
  .report-body th {{
    background: #1a73e8; color: white; text-align: left;
    padding: 10px 12px; font-weight: 600;
  }}
  .report-body td {{ padding: 8px 12px; border-bottom: 1px solid #e8eaed; }}
  .report-body tr:nth-child(even) {{ background: #f8f9fa; }}
  .report-body tr:hover {{ background: #e8f0fe; }}
  .report-body blockquote {{
    border-left: 4px solid #1a73e8; padding: 12px 16px;
    background: #e8f0fe; margin: 16px 0; border-radius: 0 8px 8px 0;
  }}
  .report-body code {{ background: #f1f3f4; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
  .report-body strong {{ color: #1a73e8; }}
  .chart-container {{
    background: white; padding: 16px; margin: 20px 0;
    border-radius: 8px; border: 1px solid #e8eaed;
  }}
  .report-footer {{
    text-align: center; padding: 20px; color: #888; font-size: 0.85em; margin-top: 24px;
  }}
  @media print {{
    body {{ background: white; }}
    .report-header {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
  }}
</style>
</head>
<body>

<div class="report-header">
  <h1>{title}</h1>
  <div class="meta">{subtitle} &bull; Generated {generated_at}</div>
</div>

<div class="report-body" id="report-content"></div>

{chart_containers}

<div class="report-footer">
  Generated by OmniDesk &bull; {generated_at}
</div>

<script>
// Render markdown content
const markdown = {markdown_json};
document.getElementById('report-content').innerHTML = marked.parse(markdown);

// Render charts
const chartConfigs = {charts_json};
chartConfigs.forEach(function(cfg) {{
  const ctx = document.getElementById(cfg.id);
  if (ctx) {{
    new Chart(ctx, {{
      type: cfg.type,
      data: cfg.data,
      options: cfg.options || {{}}
    }});
  }}
}});
</script>

</body>
</html>"""


def build_report_html(title, markdown_content, charts=None, subtitle=""):
    """Build a complete HTML report from markdown content and optional Chart.js configs.

    Args:
        title: Report title
        markdown_content: Markdown string (rendered client-side via marked.js)
        charts: List of chart configs, each with {id, type, data, options}
                 e.g. [{"id": "chart1", "type": "bar", "data": {...}, "options": {...}}]
        subtitle: Optional subtitle (e.g. "Sales Report • March 2026")

    Returns:
        Complete HTML string
    """
    charts = charts or []
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Build chart canvas containers (inserted into HTML body)
    chart_html_parts = []
    for chart in charts:
        chart_html_parts.append(
            f'<div class="chart-container">'
            f'<canvas id="{chart["id"]}" height="300"></canvas>'
            f'</div>'
        )
    chart_containers = "\n".join(chart_html_parts)

    html = HTML_SHELL.format(
        title=title,
        subtitle=subtitle,
        generated_at=generated_at,
        markdown_json=json.dumps(markdown_content),
        charts_json=json.dumps(charts),
        chart_containers=chart_containers,
    )
    return html
