"""Lambda: omnidesk-invoice-generate
POST /api/invoices/generate
Input:  {order_id, tax_rate?, due_date?, notes?}
Output: Invoice row created with GST calculation, HTML invoice uploaded to S3

Uses HTML template (no external PDF library needed — Lambda-compatible).
HTML invoice can be printed/saved as PDF from browser.
"""
import json
import os
import random
import string
from datetime import datetime, timezone, timedelta
import boto3
from utils.db import get_connection
from utils.response import success, error
from utils.auth_middleware import require_auth
from utils.audit import log_action


def _generate_invoice_number():
    """Generate invoice number like INV-20260309-B4K2."""
    date_part = datetime.now(timezone.utc).strftime("%Y%m%d")
    rand_part = "".join(random.choices(string.ascii_uppercase + string.digits, k=4))
    return f"INV-{date_part}-{rand_part}"


def _build_invoice_html(invoice_data, items, order):
    """Build a clean HTML invoice with GST support."""
    items_html = ""
    for i, item in enumerate(items, 1):
        items_html += f"""
        <tr>
            <td>{i}</td>
            <td>{item['product_name']}<br><small style="color:#666">{item['sku']}</small></td>
            <td style="text-align:center">{item['quantity']}</td>
            <td style="text-align:right">₹{item['unit_price']:.2f}</td>
            <td style="text-align:right">₹{item['total_price']:.2f}</td>
        </tr>"""

    tax_row = ""
    if invoice_data["tax_rate"] > 0:
        tax_row = f"""
        <tr>
            <td colspan="4" style="text-align:right"><strong>GST ({invoice_data['tax_rate']}%)</strong></td>
            <td style="text-align:right">₹{invoice_data['tax_amount']:.2f}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Invoice {invoice_data['invoice_number']}</title>
<style>
body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #333; }}
.header {{ display: flex; justify-content: space-between; margin-bottom: 30px; }}
.company {{ font-size: 24px; font-weight: bold; color: #2563eb; }}
.invoice-title {{ font-size: 28px; color: #1e293b; }}
.meta {{ display: flex; justify-content: space-between; margin-bottom: 30px; }}
.meta-block {{ background: #f8fafc; padding: 15px; border-radius: 8px; min-width: 200px; }}
.meta-block h4 {{ margin: 0 0 8px 0; color: #64748b; font-size: 12px; text-transform: uppercase; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
th {{ background: #1e293b; color: white; padding: 12px; text-align: left; }}
td {{ padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }}
.totals td {{ font-weight: bold; }}
.footer {{ margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; }}
@media print {{ body {{ margin: 20px; }} }}
</style>
</head>
<body>
<div class="header">
    <div class="company">OmniDesk</div>
    <div class="invoice-title">INVOICE</div>
</div>

<div class="meta">
    <div class="meta-block">
        <h4>Invoice Details</h4>
        <p><strong>{invoice_data['invoice_number']}</strong></p>
        <p>Date: {invoice_data['created_at']}</p>
        <p>Due: {invoice_data['due_date'] or 'On receipt'}</p>
    </div>
    <div class="meta-block">
        <h4>Bill To</h4>
        <p><strong>{order['customer_name']}</strong></p>
        <p>{order.get('customer_email') or ''}</p>
        <p>{order.get('customer_phone') or ''}</p>
    </div>
    <div class="meta-block">
        <h4>Order Reference</h4>
        <p><strong>{order['order_number']}</strong></p>
        <p>Status: {order['status']}</p>
    </div>
</div>

<table>
<thead>
    <tr><th>#</th><th>Item</th><th style="text-align:center">Qty</th><th style="text-align:right">Unit Price</th><th style="text-align:right">Amount</th></tr>
</thead>
<tbody>
    {items_html}
</tbody>
<tfoot class="totals">
    <tr>
        <td colspan="4" style="text-align:right"><strong>Subtotal</strong></td>
        <td style="text-align:right">₹{invoice_data['subtotal']:.2f}</td>
    </tr>
    {tax_row}
    <tr style="font-size:18px">
        <td colspan="4" style="text-align:right"><strong>Total</strong></td>
        <td style="text-align:right"><strong>₹{invoice_data['total_amount']:.2f}</strong></td>
    </tr>
</tfoot>
</table>

<div class="footer">
    <p>Generated by OmniDesk | Thank you for your business</p>
</div>
</body>
</html>"""


def _handler(event, context):
    body = json.loads(event.get("body") or "{}")
    user = event["user"]

    order_id = body.get("order_id")
    tax_rate = body.get("tax_rate", 0)
    due_date = body.get("due_date")
    notes = (body.get("notes") or "").strip() or None

    if not order_id:
        return error("order_id is required", 400)

    try:
        tax_rate = float(tax_rate)
        if tax_rate < 0 or tax_rate > 100:
            raise ValueError
    except (ValueError, TypeError):
        return error("tax_rate must be a number between 0 and 100", 400)

    conn = get_connection()
    try:
        cur = conn.cursor()

        # Get order
        cur.execute(
            """SELECT id, order_number, customer_name, customer_email, customer_phone,
                      status, subtotal, total_amount
               FROM orders WHERE id = %s""",
            (order_id,),
        )
        order = cur.fetchone()
        if not order:
            return error("Order not found", 404)

        order_data = {
            "order_number": order[1], "customer_name": order[2],
            "customer_email": order[3], "customer_phone": order[4],
            "status": order[5],
        }

        # Check if invoice already exists for this order
        cur.execute("SELECT id, invoice_number FROM invoices WHERE order_id = %s", (order_id,))
        existing = cur.fetchone()
        if existing:
            return error(f"Invoice {existing[1]} already exists for this order", 409)

        # Get order items
        cur.execute(
            """SELECT oi.product_id, p.name, p.sku, oi.quantity, oi.unit_price, oi.total_price
               FROM order_items oi JOIN products p ON oi.product_id = p.id
               WHERE oi.order_id = %s""",
            (order_id,),
        )
        items = [
            {"product_id": str(r[0]), "product_name": r[1], "sku": r[2],
             "quantity": r[3], "unit_price": float(r[4]), "total_price": float(r[5])}
            for r in cur.fetchall()
        ]
        if not items:
            return error("Order has no items", 400)

        # Calculate totals
        subtotal = sum(item["total_price"] for item in items)
        tax_amount = round(subtotal * tax_rate / 100, 2)
        total_amount = round(subtotal + tax_amount, 2)

        # Generate invoice number
        invoice_number = _generate_invoice_number()
        for _ in range(5):
            cur.execute("SELECT id FROM invoices WHERE invoice_number = %s", (invoice_number,))
            if not cur.fetchone():
                break
            invoice_number = _generate_invoice_number()

        # Default due date: 30 days from now
        if not due_date:
            due_date_obj = datetime.now(timezone.utc) + timedelta(days=30)
            due_date = due_date_obj.strftime("%Y-%m-%d")

        created_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")

        invoice_data = {
            "invoice_number": invoice_number,
            "subtotal": subtotal,
            "tax_rate": tax_rate,
            "tax_amount": tax_amount,
            "total_amount": total_amount,
            "due_date": due_date,
            "created_at": created_at,
        }

        # Build HTML invoice
        html_content = _build_invoice_html(invoice_data, items, order_data)

        # Upload to S3
        s3_key = f"invoices/{invoice_number}.html"
        s3_bucket = os.environ.get("S3_BUCKET", "omnidesk-files-577397739686")
        s3 = boto3.client("s3", region_name="us-east-1")
        s3.put_object(
            Bucket=s3_bucket,
            Key=s3_key,
            Body=html_content.encode("utf-8"),
            ContentType="text/html",
        )

        # Insert invoice row
        cur.execute(
            """INSERT INTO invoices (invoice_number, order_id, pdf_s3_key, subtotal, tax_rate,
                   tax_amount, total_amount, payment_status, status, due_date, created_by)
               VALUES (%s, %s, %s, %s, %s, %s, %s, 'unpaid', 'generated', %s, %s)
               RETURNING id, created_at""",
            (invoice_number, order_id, s3_key, subtotal, tax_rate,
             tax_amount, total_amount, due_date, user["user_id"]),
        )
        inv_row = cur.fetchone()
        conn.commit()

        invoice_id = str(inv_row[0])
        log_action(user["user_id"], "generate_invoice", "invoices", entity_id=invoice_id,
                   details={"invoice_number": invoice_number, "order_number": order_data["order_number"],
                            "total": str(total_amount), "tax_rate": str(tax_rate)})

        return success({
            "id": invoice_id,
            "invoice_number": invoice_number,
            "order_id": str(order_id),
            "order_number": order_data["order_number"],
            "customer_name": order_data["customer_name"],
            "subtotal": str(subtotal),
            "tax_rate": str(tax_rate),
            "tax_amount": str(tax_amount),
            "total_amount": str(total_amount),
            "payment_status": "unpaid",
            "status": "generated",
            "s3_key": s3_key,
            "due_date": due_date,
            "created_at": str(inv_row[1]),
        }, 201)
    except Exception as e:
        conn.rollback()
        return error(f"Failed to generate invoice: {str(e)}", 500)
    finally:
        conn.close()


handler = require_auth(_handler, min_role="manager")


def lambda_handler(event, context):
    if event.get("httpMethod") == "OPTIONS":
        return success({}, 204)
    return handler(event, context)
